spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: user
    password: pass
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate.format_sql: true

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml

app:
  jwt:
    secret: very-long-random-string-change-in-prod-please
    expiration-ms: 3600000

server:
  port: 8080